builders:
  auto_mapper_generator:
    import: "package:auto_mapper/src/generators/auto_mapper_generator.dart"
    builder_factories: ["autoMapperBuilder"]
    build_extensions: { "$package$": ["lib/auto_mapper.dart"] }
    auto_apply: dependents
    build_to: source
