name: auto_mapper
description: "Package to generate mappers for your models, using annotations and code generation."
version: 1.0.2
homepage: https://github.com/Luciano-Magnus/auto_mapper/blob/main/README.md

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  dart_style: ^3.0.1
  glob: ^2.1.3
  source_gen: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^3.0.0
