name: auto_mapper
description: "A new Flutter project."
version: 1.0.1
homepage: https://github.com/Luciano-Magnus/auto_mapper/blob/main/README.md

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^7.3.0
  build: ^2.4.2
  source_gen: ^2.0.0
  glob: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
